# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack Torrance",
  "email": "torans@overlook.net",
  "type": "ordinary",
  "password": "shining"
}

###

## Создать нового пользователя с аватаром

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="name"

Jack Torrance
--MyBoundary
Content-Disposition: form-data; name="email"

torans-avatar@overlook.net
--MyBoundary
Content-Disposition: form-data; name="type"

ordinary
--MyBoundary
Content-Disposition: form-data; name="password"

shining
--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< ../../../../upload/default-avatar.png
--MyBoundary--

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Загрузить аватар пользователя

POST http://localhost:4000/users/avatar HTTP/1.1
Authorization: Bearer <token>
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="default-avatar.png"
Content-Type: image/png

< ../../../../static/default-avatar.png
--MyBoundary--

###

## Проверить состояние авторизации

GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer <token>

###