# Предложения
## Создать новое объявление
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Уютная студия в центре Берлина",
  "description": "Светлая студия с современным ремонтом. Рядом кафе, магазины и транспортная развязка. Идеально для одного или пары.",
  "postDate": "2026-04-19T10:00:00.000Z",
  "city": "Berlin",
  "previewPath": "studio-berlin.jpg",
  "images": [
    "studio-1.jpg",
    "studio-2.jpg",
    "studio-3.jpg"
  ],
  "isPremium": true,
  "rating": 4.8,
  "type": "Apartment",
  "roomsCount": 1,
  "guestsCount": 2,
  "price": 85000,
  "conveniences": [
    "Wi-Fi",
    "Kitchen",
    "Heating"
  ],
  "coordinates": {
    "latitude": 52.520008,
    "longitude": 13.404954
  }
}

###

## Получить список объявлений
GET http://localhost:4000/offers HTTP/1.1

###

## Получить объявление по идентификатору
GET http://localhost:4000/offers/6a0afba967ac70914fb8a75e HTTP/1.1

###

## Удалить объявление по идентификатору
DELETE http://localhost:4000/offers/6a0afba967ac70914fb8a75e HTTP/1.1

###

## Изменить объявление по идентификатору
PATCH http://localhost:4000/offers/6a0afba967ac70914fb8a75e HTTP/1.1
Content-Type: application/json

{
  "title": "Роскошный пентхаус с видом на реку",
  "description": "Просторные апартаменты на последнем этаже. Панорамные окна, терраса и высокие потолки. Престижный район.",
  "city": "Hamburg",
  "previewPath": "penthouse-hamburg.jpg",
  "images": [
    "penthouse-1.jpg",
    "penthouse-2.jpg",
    "penthouse-3.jpg"
  ],
  "isPremium": true,
  "rating": 4.9,
  "type": "Penthouse",
  "roomsCount": 4,
  "guestsCount": 6,
  "price": 250000,
  "conveniences": [
    "Wi-Fi",
    "Parking",
    "Elevator",
    "Dishwasher",
    "Air conditioning"
  ],
  "coordinates": {
    "latitude": 53.551086,
    "longitude": 9.993682
  }
}

###

## Получить премиальные по городу
GET http://localhost:4000/offers/premium/Paris HTTP/1.1

###

## Получить список избранных
GET http://localhost:4000/offers/favorite HTTP/1.1

###

## Добавить объявление в избранные
POST http://localhost:4000/offers/favorite/6a0afba967ac70914fb8a75e HTTP/1.1

###

## Удалить объявление из избранных
DELETE http://localhost:4000/offers/favorite/6a0afba967ac70914fb8a75e HTTP/1.1

###