export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  CliApplication: Symbol.for('CliApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserModel: Symbol.for('UserModel'),
  OfferService: Symbol.for('OfferService'),
  OfferModel: Symbol.for('OfferModel'),
  OfferController: Symbol.for('OfferController'),
  CommentService: Symbol.for('CommentService'),
  CommentModel: Symbol.for('CommentModel'),
  CommentController: Symbol.for('CommentController'),
  CategoryController: Symbol.for('CategoryController'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  UserController: Symbol.for('UserController'),
  HelpCommand: Symbol.for('HelpCommand'),
  ImportCommand: Symbol.for('ImportCommand'),
  VersionCommand: Symbol.for('VersionCommand'),
  GenerateCommand: Symbol.for('GenerateCommand'),
  AuthService: Symbol.for('AuthService'),
  AuthExceptionFilter: Symbol.for('AuthExceptionFilter'),
  PathTransformer: Symbol.for('PathTransformer'),
} as const;
